### ISSUE TITLE
the cross platform void luancher doesnt work

### ISSUE THREAD

**Issue by DKLYNTLY** [Voidswrath-Support/Bug-reports#26]
**Describe the bug**
No modpacks show up just the animations and  a blank screen with no modpacks

**Steps to reproduce**
How to reproduce the bug goes here. 
For example:
Step 1: Click download
Step 2: Launch it

**Expected Behavior**
modpacks to show

**Screenshots**

<img width="1280" alt="Screen Shot 2021-10-19 at 8 15 00 PM" src="https://user-images.githubusercontent.com/75499681/138007303-41ca3448-cb6d-478c-9c1c-7185cecbfbe5.png">
<details>
  <summary><strong>Game Output</strong></summary>

```
Ads Initializing....
Adding popup
Complete...
Initializing table...
Content Type of text/plain; charset=UTF-8 acceptable. Continuing...
Downloading version info...
3.2.2.8
Fixed the issues when an invalid login is entered, and play is pressed before hitting the login button. :Added an alert if you leave the username field blank, for good measure.:3.2.2.7:Spotlighting of modpacks added.:Additional information added to modpack view:3.2.2.6:Fixes an environment detection bug, causing some modpacks to fail to launch:3.2.2.5:Fixed an issue causing modpacks to reinstall if using microsoft login.:3.2.2.4:Fixed 1.7.10 modpacks launching issues caused by the 1.16.4 update.:3.2.2.3:Support added for 1.16.4 modpacks:3.2.2.2:Improved Microsoft Login Compatibility:3.2.2.1:Added more descriptive errors on sign in:Improved the microsoft login backdrop:3.2.2.0:Fixed a minecraft login issue on some configurations.:3.2.1.9:Fixed a minecraft login issue on some configurations.:3.2.1.8:Added first installation precache for a better experience for first installers.:Fixed jni errors with older modpacks:3.2.1.7:Added Microsoft Login Support:3.2.1.4:Fixed issues with library downloading for 1.6.4 modpacks.:3.2.1.3:News Feed Removed:Fix for an issue that could cause the launcher to fail to startup.:Fixed an issue that could cause the launcher to fail to save settings.:3.2.1.2:Fix for an issue that caused the launcher to stay locked in the background:3.2.1.1:Fix for links being wrong after sorting:3.2.1.0:UI rendering fixes:3.2.0.9:Fixes an issue that could cause a modpack reinstallation:to rollback your world:3.2.0.8:Fixes for modpack update alert:Added automatic backup alert when reinstalling:3.2.0.6:Bug fixes:New login system added that is less confusing:Many quality of life improvements and simplifications:3.2.0.5:Fixed an issue causing some links to not work correctly:3.2.0.4:Formatting fixes:Fixed an issue with settings not saving:3.2.0.3:Made it so modpacks are only reinstalled when you ask it to.:3.2.0.2:Made the options pane easier to understand what is going on.:3.2.0.1:Fixed username and password saving.:Fixed portrait lookups for usernames.:3.1.3.0:Upped default ram when 64-bit java is detected for better modpack compatibility:Temporarily disabled the mods and server tab.:Fixed a bug which could cause loss of settings on launcher restart.:3.1.2.9:Added startup check for windows that will check if you are running a 32-bit java installation in 64-bit.:Added optional automatic downloader for java if you are using the wrong version.:3.1.2.8:Fix for PermFix being stuck on in Java 8 and causing VM Crashes.:Fixed some expired library locations causing some modpacks to unsuccessfully install for new users.:3.1.2.7:Many UI updates:Fixes some issues with the launch the first time it is launched on a machine.:Added gameband support.:3.1.2.6:Fixed an issue with libraries failing to validate.:Added support for forge 1.8.0:3.1.2.5:Fixed an issue that could cause the launcher to lockup on startup:Performance/threading tweaks:Reduced the amount of downloading by sharing identical files between modpacks:3.1.2.4:Much log spam cleanup. :Improved session saving across VoidLauncher launches.:3.1.2.3:Updated for better session sharing between minecraft and voidlauncher.:3.1.2.2:Fixed a JVM crash:Fixed an issue with loading modpack info on some languages.:3.1.2.1:Added better support on MacOSX for java installations not set as the global default:3.1.2.0:Performance tweak to the log to prevent memory leaking from modpacks that spam the console.:Log automatically created for convenience and better diagnosis of issues.:3.1.1.9:Bug fix correcting possible lockups on some systems.:3.1.1.8:Fixed duplicate modpacks and performance issues on the modpack tab.:3.1.1.7:Small hotfix:3.1.1.6:Additional UI Fixes:Added Support for minor modpack version updates.:3.1.1.5:Small UI fix.:3.1.1.4:Fix for a startup crash on OSX.:3.1.1.3:UI Updates.:Added the ability to use a seperate folder/drive for your modpack installations.:3.1.1.2:Fixed an issue which could cause macs not to launch.:3.1.1.1:Improved java installation detection.:3.1.1.0:Fixed an deadlock circumstance when X'ing out a modpack loading screen.:3.1.0.9:Fixed an issue that causes MD5's to not get checked.:3.1.0.8:Fixed an issue which causes things to not be cleaned up properly on reinstall.:3.1.0.7:Fixed an issue which could cause the save folder to be deleted.:
Update check complete...
Complete
Initializing Popup menu...
Popup menu initialized...
Initializing Home pane...
Initializing List...
List Selection Listener...
List Complete...
Setting Opaque statuses...
Setting Window Opacity...
Finalizing...
this.setLocationRelativeTo(null)
VoidLauncher Creation Successful!
Queuing up Modpack Updater...
Syncing...
Done...
Loading...
Downloading new modpack info...
Downloading Modpack info
Done...
Detected Arch:
Arch: x86_64 Is 64-bit? true
Detected Processor Cores:
Cores: 4
Java home: /Library/Java/JavaVirtualMachines/jdk-16.jdk/Contents/Home
Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/bin/java
Detected free memory:
161/8192 MB
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:679)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:456)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:381)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:336)
	at com.voidswrath.voidlauncher.VoidLauncher.downloadModPackInfo(VoidLauncher.java:4116)
	at com.voidswrath.voidlauncher.VoidLauncher$loadModPackInfo.run(VoidLauncher.java:3897)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Reading Username...
Username Read...
Syncing...
Done...
Loading...
Done...
Detected Arch:
Arch: x86_64 Is 64-bit? true
Detected Processor Cores:
Cores: 4
Java home: /Library/Java/JavaVirtualMachines/jdk-16.jdk/Contents/Home
Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/bin/java
Detected free memory:
87/8192 MB
Made It To End...
[CrazyCraft4, ScrambleCraft2]
java.lang.ClassCastException: class javax.swing.JList$3 cannot be cast to class javax.swing.DefaultListModel (javax.swing.JList$3 and javax.swing.DefaultListModel are in module java.desktop of loader 'bootstrap')
	at com.voidswrath.voidlauncher.VoidConfig.saveConfig(VoidConfig.java:685)
	at com.voidswrath.voidlauncher.VoidLauncher$8.actionPerformed(VoidLauncher.java:1150)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:679)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:456)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:381)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:336)
	at com.voidswrath.voidlauncher.FilePreferences.exportNode(FilePreferences.java:330)
	at com.voidswrath.voidlauncher.VoidConfig.saveConfig(VoidConfig.java:705)
	at com.voidswrath.voidlauncher.VoidLauncher$8.actionPerformed(VoidLauncher.java:1150)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

<details>
  <summary><strong>Crash Report</strong></summary>

```
Ads Initializing....
Adding popup
Complete...
Initializing table...
Content Type of text/plain; charset=UTF-8 acceptable. Continuing...
Downloading version info...
3.2.2.8
Fixed the issues when an invalid login is entered, and play is pressed before hitting the login button. :Added an alert if you leave the username field blank, for good measure.:3.2.2.7:Spotlighting of modpacks added.:Additional information added to modpack view:3.2.2.6:Fixes an environment detection bug, causing some modpacks to fail to launch:3.2.2.5:Fixed an issue causing modpacks to reinstall if using microsoft login.:3.2.2.4:Fixed 1.7.10 modpacks launching issues caused by the 1.16.4 update.:3.2.2.3:Support added for 1.16.4 modpacks:3.2.2.2:Improved Microsoft Login Compatibility:3.2.2.1:Added more descriptive errors on sign in:Improved the microsoft login backdrop:3.2.2.0:Fixed a minecraft login issue on some configurations.:3.2.1.9:Fixed a minecraft login issue on some configurations.:3.2.1.8:Added first installation precache for a better experience for first installers.:Fixed jni errors with older modpacks:3.2.1.7:Added Microsoft Login Support:3.2.1.4:Fixed issues with library downloading for 1.6.4 modpacks.:3.2.1.3:News Feed Removed:Fix for an issue that could cause the launcher to fail to startup.:Fixed an issue that could cause the launcher to fail to save settings.:3.2.1.2:Fix for an issue that caused the launcher to stay locked in the background:3.2.1.1:Fix for links being wrong after sorting:3.2.1.0:UI rendering fixes:3.2.0.9:Fixes an issue that could cause a modpack reinstallation:to rollback your world:3.2.0.8:Fixes for modpack update alert:Added automatic backup alert when reinstalling:3.2.0.6:Bug fixes:New login system added that is less confusing:Many quality of life improvements and simplifications:3.2.0.5:Fixed an issue causing some links to not work correctly:3.2.0.4:Formatting fixes:Fixed an issue with settings not saving:3.2.0.3:Made it so modpacks are only reinstalled when you ask it to.:3.2.0.2:Made the options pane easier to understand what is going on.:3.2.0.1:Fixed username and password saving.:Fixed portrait lookups for usernames.:3.1.3.0:Upped default ram when 64-bit java is detected for better modpack compatibility:Temporarily disabled the mods and server tab.:Fixed a bug which could cause loss of settings on launcher restart.:3.1.2.9:Added startup check for windows that will check if you are running a 32-bit java installation in 64-bit.:Added optional automatic downloader for java if you are using the wrong version.:3.1.2.8:Fix for PermFix being stuck on in Java 8 and causing VM Crashes.:Fixed some expired library locations causing some modpacks to unsuccessfully install for new users.:3.1.2.7:Many UI updates:Fixes some issues with the launch the first time it is launched on a machine.:Added gameband support.:3.1.2.6:Fixed an issue with libraries failing to validate.:Added support for forge 1.8.0:3.1.2.5:Fixed an issue that could cause the launcher to lockup on startup:Performance/threading tweaks:Reduced the amount of downloading by sharing identical files between modpacks:3.1.2.4:Much log spam cleanup. :Improved session saving across VoidLauncher launches.:3.1.2.3:Updated for better session sharing between minecraft and voidlauncher.:3.1.2.2:Fixed a JVM crash:Fixed an issue with loading modpack info on some languages.:3.1.2.1:Added better support on MacOSX for java installations not set as the global default:3.1.2.0:Performance tweak to the log to prevent memory leaking from modpacks that spam the console.:Log automatically created for convenience and better diagnosis of issues.:3.1.1.9:Bug fix correcting possible lockups on some systems.:3.1.1.8:Fixed duplicate modpacks and performance issues on the modpack tab.:3.1.1.7:Small hotfix:3.1.1.6:Additional UI Fixes:Added Support for minor modpack version updates.:3.1.1.5:Small UI fix.:3.1.1.4:Fix for a startup crash on OSX.:3.1.1.3:UI Updates.:Added the ability to use a seperate folder/drive for your modpack installations.:3.1.1.2:Fixed an issue which could cause macs not to launch.:3.1.1.1:Improved java installation detection.:3.1.1.0:Fixed an deadlock circumstance when X'ing out a modpack loading screen.:3.1.0.9:Fixed an issue that causes MD5's to not get checked.:3.1.0.8:Fixed an issue which causes things to not be cleaned up properly on reinstall.:3.1.0.7:Fixed an issue which could cause the save folder to be deleted.:
Update check complete...
Complete
Initializing Popup menu...
Popup menu initialized...
Initializing Home pane...
Initializing List...
List Selection Listener...
List Complete...
Setting Opaque statuses...
Setting Window Opacity...
Finalizing...
this.setLocationRelativeTo(null)
VoidLauncher Creation Successful!
Queuing up Modpack Updater...
Syncing...
Done...
Loading...
Downloading new modpack info...
Downloading Modpack info
Done...
Detected Arch:
Arch: x86_64 Is 64-bit? true
Detected Processor Cores:
Cores: 4
Java home: /Library/Java/JavaVirtualMachines/jdk-16.jdk/Contents/Home
Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/bin/java
Detected free memory:
161/8192 MB
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:679)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:456)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:381)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:336)
	at com.voidswrath.voidlauncher.VoidLauncher.downloadModPackInfo(VoidLauncher.java:4116)
	at com.voidswrath.voidlauncher.VoidLauncher$loadModPackInfo.run(VoidLauncher.java:3897)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Reading Username...
Username Read...
Syncing...
Done...
Loading...
Done...
Detected Arch:
Arch: x86_64 Is 64-bit? true
Detected Processor Cores:
Cores: 4
Java home: /Library/Java/JavaVirtualMachines/jdk-16.jdk/Contents/Home
Command: /Library/Java/JavaVirtualMachines/jdk1.8.0_301.jdk/Contents/Home/jre/bin/java
Detected free memory:
87/8192 MB
Made It To End...
[CrazyCraft4, ScrambleCraft2]
java.lang.ClassCastException: class javax.swing.JList$3 cannot be cast to class javax.swing.DefaultListModel (javax.swing.JList$3 and javax.swing.DefaultListModel are in module java.desktop of loader 'bootstrap')
	at com.voidswrath.voidlauncher.VoidConfig.saveConfig(VoidConfig.java:685)
	at com.voidswrath.voidlauncher.VoidLauncher$8.actionPerformed(VoidLauncher.java:1150)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.NoClassDefFoundError: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:679)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:456)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:381)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:336)
	at com.voidswrath.voidlauncher.FilePreferences.exportNode(FilePreferences.java:330)
	at com.voidswrath.voidlauncher.VoidConfig.saveConfig(VoidConfig.java:705)
	at com.voidswrath.voidlauncher.VoidLauncher$8.actionPerformed(VoidLauncher.java:1150)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6382)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

<details>
  <summary><strong>Additional Information</strong></summary>

- Launcher bug [Y/N]:  yes
- Modpack: 
- Additional mods:  no
- Operating system:  macos

</details>

**Additional Information**
List any additional information you wish to provide.

**Comment by DKLYNTLY** [comment]
bruh no help i see how it is

**Comment by ghost** [comment]
they dont care lmao

**Comment by ghost** [comment]
> bruh no help i see how it is

just download the modpack zip it helps alot
